name: Vote-System
version: '1.0'
main: net.exsar.votesystem.VoteSystem
api-version: '1.21'
author: Ensar
description: Testaufgabe für GermanMinerDE

commands:
  tokenadmin:
    permission: votesystem.edittoken
    description: Veränderung der Tokens von Spielern.
  vote:
    description: Vote-Befehl, lol